version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/fastapi_python_starter
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: fastapi_python_starter_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/fastapi_python_starter_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=fastapi_python_starter, fastapi_python_starter_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
